export const SET_WEATHER = "SET_WEATHER"
export const SET_FAVORITE = "SET_FAVORITE"
export const SET_MODE = "SET_MODE"
export const DEL_FAVORITE = "DEL_FAVORITE"
export const SET_LOCATION = "SET_LOCATION"